export const queryKeys = {
  me: ['users', 'me'] as const,
  publicProfile: (userId: string) => ['users', 'profile', userId] as const,
  market: (filters?: Record<string, unknown>) => ['market', filters] as const,
  marketProduct: (id: string) => ['market', id] as const,
  crops: (status?: string) => ['products', status] as const,
  crop: (id: string) => ['products', id] as const,
  farms: ['farms'] as const,
  farm: (id: string) => ['farms', id] as const,
  myOrders: ['orders', 'my'] as const,
  incomingOrders: ['orders', 'incoming'] as const,
  order: (id: string) => ['orders', id] as const,
  wallet: ['wallet'] as const,
  walletTransactions: ['wallet', 'transactions'] as const,
  withdrawals: ['wallet', 'withdrawals'] as const,
  bankAccounts: ['bank-accounts'] as const,
  payments: ['payments'] as const,
  notifications: ['notifications'] as const,
  unreadCount: ['notifications', 'unread-count'] as const,
  ratingsReceived: ['ratings', 'me'] as const,
  ratingsGiven: ['ratings', 'given'] as const,
  categories: ['categories'] as const,
};
